/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    { type: 'category', label: 'Getting Started', items: [{ type: 'autogenerated', dirName: 'overview' }] },
    { type: 'category', label: 'Guides', items: [{ type: 'autogenerated', dirName: 'guides' }] },
    { 
      type: 'category', 
      label: 'Platforms', 
      link: { type: 'doc', id: 'platforms/overview' }, 
      items: [{ type: 'autogenerated', dirName: 'platforms' }] 
    },
    { type: 'category', label: 'Engines', items: [{ type: 'autogenerated', dirName: 'engines' }] },
    { type: 'doc', 'id': 'templates/overview' },
    { type: 'doc', 'id': 'plugins/overview' },
    { type: 'category', label: 'Integrations', items: [{ type: 'autogenerated', dirName: 'integrations' }] },
    { type: 'category', label: 'Upgrades', items: [{ type: 'autogenerated', dirName: 'upgrades' }] },
    { label: 'Release Notes', type: 'link', href: 'https://github.com/flexn-io/renative/releases' }
],
apiSidebar: [
    { type: 'autogenerated', dirName: 'api' },
],

  // tutorialSidebar: [
  //   { type: 'autogenerated', dirName: 'tutorials' },
  // ],
  // referenceSidebar: [
  //   { type: 'autogenerated', dirName: 'references' },
  // ],
  // apiSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Descriptor',
  //     link: {
  //       type: 'generated-index',
  //       title: 'Descriptor',
  //       description: 'description',
  //       slug: 'descriptor',
  //       keywords: ['descriptor'],
  //     },
  //     items: [
  //       {
  //         type: 'category',
  //         label: 'Project',
  //         link: {
  //           type: 'generated-index',
  //           title: 'Project',
  //           description: 'description',
  //           slug: 'project',
  //           keywords: ['project'],
  //         },
  //         items: [{ type: 'autogenerated', dirName: 'api' }]
  //       },
  //       {
  //         type: 'category',
  //         label: 'App',
  //         link: {
  //           type: 'generated-index',
  //           title: 'App',
  //           description: 'description',
  //           slug: 'app',
  //           keywords: ['app'],
  //         },
  //         items: [{ type: 'autogenerated', dirName: 'changelog' }]
  //       },
  //     ]
  //   },
  //   {
  //     type: 'category',
  //     label: 'Runtime',
  //     link: {
  //       type: 'generated-index',
  //       title: 'Runtime',
  //       description: 'description',
  //       slug: 'runtime',
  //       keywords: ['runtime'],
  //     },
  //     items: [{ type: 'autogenerated', dirName: 'upgrades' }]
  //   },
  //   {
  //     type: 'category',
  //     label: 'Node',
  //     link: {
  //       type: 'generated-index',
  //       title: 'Node',
  //       description: 'description',
  //       slug: 'node',
  //       keywords: ['node'],
  //     },
  //     items: [{ type: 'autogenerated', dirName: 'engines' }]
  //   },
  //   {
  //     type: 'category',
  //     label: 'Rnv CLI',
  //     link: {
  //       type: 'generated-index',
  //       title: 'Rnv CLI',
  //       description: 'description',
  //       slug: 'rnvcli',
  //       keywords: ['rnvcli'],
  //     },
  //     items: [{ type: 'autogenerated', dirName: 'integrations' }]
  //   },
  // ],
  // marketSidebar: [
  //   {
  //     type: 'doc',
  //     'id': 'marketplace/templates'
  //   },
  //   {
  //     type: 'doc',
  //     'id': 'marketplace/plugins'
  //   },
  //   {
  //     type: 'category',
  //     label: 'Integrations',
  //     link: {
  //       type: 'generated-index',
  //       title: 'Integrations',
  //       description: 'description',
  //       slug: 'integrations',
  //       keywords: ['integrations'],
  //     },
  //     items: [{ type: 'autogenerated', dirName: 'integrations' }]
  //   },
  //   {
  //     type: 'category',
  //     label: 'Engines',
  //     link: { type: 'doc', id: 'marketplace/engines' },
  //     items: [{ type: 'autogenerated', dirName: 'engines' }]
  //   },
  //   {
  //     type: 'doc',
  //     'id': 'marketplace/build_hooks'
  //   },
  // ],
  // conceptsSidebar: [
  //   { type: 'autogenerated', dirName: 'concepts' },
  // ],
  // releasesSidebar: [
  //   {
  //     type: 'doc',
  //     'id': 'releases/releasenotes'
  //   },
  //   {
  //     type: 'doc',
  //     'id': 'releases/socialmedia'
  //   },
  //   {
  //     type: 'category',
  //     label: 'Upgrades',
  //     link: {
  //       type: 'generated-index',
  //       title: 'Upgrades',
  //       description: 'description',
  //       slug: 'upgrades',
  //       keywords: ['upgrades'],
  //     },
  //     items: [{ type: 'autogenerated', dirName: 'upgrades' }]
  //   },
  // ],
};

module.exports = sidebars;
